##디렉토리 설정##
setwd("D:/")
##패키지 설치##
install.packages("arules")
install.packages("arulesViz")
library(arules)
library(arulesViz)
Bank1 = read.csv("BNKSERV.csv")
count<-table(Bank1$SERVICE)
table<-data.frame(freq=count)
mosaicplot(~SERVICE,data=Bank1,color=TRUE)
plot1<-plot(Bank1$SERVICE)
ggplot(Bank1,aes(x=table$freq.Var1,y=table$freq.Freq))
Bank = read.transactions("BNKSERV.csv", format = "single", cols = c(1,2), sep=",", skip=1)
inspect(Bank)
str(Bank)
as(Bank,"data.frame")[1:10,]
rules = apriori(Bank, parameter=list(support=0.1, confidence=0.7, minlen=2),control=list(verbose=F))
rules.sorted = sort(rules, by=c("support","lift"))
inspect(rules.sorted)
rules.sub = subset(rules, subset =lift > 1) 
inspect(rules.sub)
plot(rules, method="graph", interactive=TRUE)
plot(rules, method="grouped", measure=c("lift","support"))
